### PR TITLE
Egui 0.22.0

### PR DESCRIPTION
**Pull request by dklassic**
Closes <https://github.com/emilk/egui/issues/THE_RELEVANT_ISSUE>.

### CODE REVIEW

**Comment by dklassic** [comment]
This is a WIP to upgrade `egui` to 0.22.0, modifications have been made on `eframe`, `egui-winit`, `egui-wgpu` to make use of `tao`.
This currently fully works on Windows 11, macOS Ventura and are both capable to build and run `egui_demo_app` properly.

I'm currently having issue to make it run on both X11 and Wayland, which accidentally leads to the discovery and fix of https://github.com/tauri-apps/tao/pull/741 but it's generally irrelevant to the problem I'm having here.

On Wayland, the build can be completed for `egui_demo_app`, but the app does not show properly.
On X11, the build can also be completed for `egui_demo_app`, but an error shows up that indicates `Requested usage is not supported` when configuring surface within `wgpu`, which is caused by `eframe` using `egui-wgpu::winit::Painter::set_window` in `eframe\src\native\run.rs:1141`.

**Comment by ctaggart** [comment]
I'm sad that this was not completed. Thank for attempting @dklassic.

**Comment by dklassic** [comment]
> I'm sad that this was not completed. Thank for attempting @dklassic.

No worries, I'm still working on it!
gtk3 does not support Vulkan context so we're reevaluating our options here.

**Comment by dklassic** [comment]
Reworked the upgrade using glutin, have it working on Windows and macOS, egui_demo_app runs just fine.
I'm still figuring out a weird behavior on X11 that leads to an `Glutin(Error { raw_code: Some(12299), raw_os_message: None, kind: BadNativeWindow })`

Full log:
```
[2023-06-12T04:33:27Z DEBUG eframe] Using the glow renderer
[2023-06-12T04:33:27Z DEBUG eframe::native::run] Entering the winit event loop (run_return)…
[2023-06-12T04:33:27Z DEBUG eframe::native::file_storage] Loading app state from "/home/wusyong/.local/share/eguidemoapp/app.ron"…
[2023-06-12T04:33:27Z DEBUG eframe::native::run::glow_integration] trying to create glutin Display with config: ConfigTemplateBuilder { template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: WINDOW, api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None } }
[2023-06-12T04:33:27Z DEBUG eframe::native::run::glow_integration] using the first config from config picker closure. config: Egl(Config { inner: Config { raw: EglConfig(0x55fb9896c7e0), display: Khr(0x55fb989db2a0) } })
[2023-06-12T04:33:27Z DEBUG eframe::native::run::glow_integration] successfully created GL Display with version: EGL 1.5 and supported features: CONTEXT_ROBUSTNESS | CONTEXT_NO_ERROR | FLOAT_PIXEL_FORMAT | SWAP_CONTROL | CREATE_ES_CONTEXT | MULTISAMPLING_PIXEL_FORMATS | SRGB_FRAMEBUFFERS
[2023-06-12T04:33:27Z DEBUG eframe::native::run::glow_integration] creating gl context using raw window handle: Some(Xlib(XlibWindowHandle { window: 0, visual_id: 0 }))
[2023-06-12T04:33:27Z DEBUG eframe::native::run::glow_integration] running on_resume fn.
[2023-06-12T04:33:27Z DEBUG eframe::native::run::glow_integration] creating surface with attributes: SurfaceAttributes { srgb: None, single_buffer: false, width: Some(1320), height: Some(855), largest_pbuffer: false, raw_window_handle: Some(Xlib(XlibWindowHandle { window: 0, visual_id: 0 })), native_pixmap: None, _ty: PhantomData }
[2023-06-12T04:33:27Z ERROR eframe::native::run] Exiting because of error: Glutin(Error { raw_code: Some(12299), raw_os_message: None, kind: BadNativeWindow }) on event NewEvents(Init)
```

Tracing this issue leads to https://github.com/emilk/egui/issues/2520, which indicates the possibility of driver issue instead, but I'm not sure if this is the case here.

**Comment by dklassic** [comment]
The upgrade seems to be working now!
I'll be doing a revamp to the repository structure before readying for review.
A small note on what happened above:
egui 0.22.0 has some implementation to allow for accesskit integration, to allow accesskit work properly, the window is set to be non-visible upon creation. This causes problem for the raw_window_handle cannot be properly retrieved when using tao.

**Comment by ctaggart** [comment]
This is great! Excited to see the update. This fixes https://github.com/tauri-apps/tauri-egui/issues/18 .

**Review by wusyong — APPROVED** [review]

**Pull request merged**
